### ISSUE TITLE
Connect to localhost?

### ISSUE THREAD

**Issue by tehfailsafe** [mathieudutour/sketch-module-web-view#1]
Trying to setup webpack-dev-server to push hot changes to the Resources index.html file.
I've tried two approaches so far (both https, seems AppTransport has an issue with non-https)

1.  Connecting via the new WebUI call:
`new WebUI(context, 'https://localhost:8080', options)`
Error: _2/13/17 1:17:20.709 PM Main Command (Sketch Plugin)[575]: TypeError: null is not an object (evaluating 'context.plugin.urlForResourceNamed(htmlName).path')_

2. Connecting in the index.html file
`<script src="https://localhost:8080"></script>`
Error: _Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made._

Think this is possible?

**Comment by mathieudutour** [comment]
hum I haven't tried.

On the top of my head: changing this line: https://github.com/mathieudutour/sketch-module-web-view/blob/master/lib/index.js#L79 to `webView.setMainFrameURL_('https://localhost:8080')` could work.

If it does, we could change the API so that you can pass a URL instead of a path

**Comment by tehfailsafe** [comment]
That still runs into the same error:
_Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made._

Does it have something to do with App Transport Security?
https://forums.developer.apple.com/thread/6767

**Comment by mathieudutour** [comment]
I'm not sure, never used https on localhost. Isn't it working with just http?

**Comment by tehfailsafe** [comment]
I tried that first, however got the following:
_Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection._

**Comment by mathieudutour** [comment]
but does `https://localhost:8080`? Did you set up the https for your localhost?

**Comment by tehfailsafe** [comment]
Yes, I setup the https so that in chrome it works correctly. In the web-view if I inspect source it shows: _Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made._

**Comment by tehfailsafe** [comment]
If it isn't possible, it's fine, I was just trying to see how far it could be pushed. I can totally work without live reloading :)

**Comment by mathieudutour** [comment]
Yeah sorry, it might be possible but not sure how and I don't have much time to experiment with it right now.

But if you find something, keep me updated :)
