### ISSUE TITLE
How to use this in a .sketchplugin?

### ISSUE THREAD

**Issue by ajilderda** [mathieudutour/sketch-module-web-view#4]
Hi Mathieu,

I've spent a few hours trying to get your module to work, but without success. Can you maybe give a few pointers on how this could be used in a .sketchplugin? A bare bone example would already be a big help.

Best,
Andre

**Comment by ajilderda** [comment]
By chance I found the missing link: [skpm](https://github.com/sketch-pm/skpm). Adding a link to the readme might save someone a headache. ;) Thanks for your work on these Mathieu!

**Comment by mathieudutour** [comment]
Yes, you need to bundle your code, skpm is one of the tools you can use to do this. 
Happy to merge a PR to clarify this in the readme
